M48
; DRILL file {KiCad (5.99.0-11630-gc5e195bdff)} date Mon Aug 23 20:37:22 2021
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2021-08-23T20:37:22+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-11630-gc5e195bdff)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X100.71Y-63.175
X106.49Y-63.175
T0
M30
